#!/usr/bin/env bash

hc() {
    herbstclient "$@"
}
hc pad 0 32 0 0 0
hc emit_hook reload

xfsettingsd 
killall -q tint2
killall -q volumeicon
# remove all existing keybindings
hc keyunbind --all

# keybindings
#Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-Control-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close

hc keybind $Mod-t spawn gnome-terminal
hc keybind $Mod-Return spawn rofi -show combi -show-icons -columns 3
hc keybind $Mod-Shift-w spawn feh --bg-scale -z -r Pictures/Wallpapers
hc keybind $Mod-Shift-a spawn flameshot gui

hc keybind $Mod-Shift-t spawn alacritty
#hc keybind $Mod-t spawn alacritty -e tmux
# basic movement
# focusing clients
#hc keybind $Mod-Left  focus left
#hc keybind $Mod-Down  focus down
#hc keybind $Mod-Up    focus up
#hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients
#hc keybind $Mod-Shift-Left  shift left
#hc keybind $Mod-Shift-Down  shift down
#hc keybind $Mod-Shift-Up    shift up
#hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
hc keybind $Mod-Shift-o split   right   0.65
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.15
resizelittlestep=0.025
hc keybind $Mod-Control-h     resize left +$resizestep
hc keybind $Mod-Control-j     resize down +$resizestep
hc keybind $Mod-Control-k     resize up +$resizestep
hc keybind $Mod-Control-l     resize right +$resizestep
hc keybind $Mod-Control-Left  resize left +$resizelittlestep
hc keybind $Mod-Control-Down  resize down +$resizelittlestep
hc keybind $Mod-Control-Up    resize up +$resizelittlestep
hc keybind $Mod-Control-Right resize right +$resizelittlestep

hc set_layout max
hc set default_frame_layout 2

# tags
tag_names=( {1..9} 0 )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle
hc keybind $Mod-c cycle_layout 1 max horizontal vertical

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-space cycle
hc keybind $Mod-i jumpto urgent

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#77AACC'
hc set frame_border_normal_color '#55AA88'
hc set frame_bg_normal_color '#55AA88'
hc set frame_bg_active_color '#77AACC'
hc set frame_border_width 4
hc set always_show_frame 1
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_gap 3

hc attr theme.active.color '#77AACC'
hc attr theme.normal.color '#55AA88'
hc attr theme.urgent.color orange
hc attr theme.inner_width 0
hc attr theme.inner_color '#55AA88'
hc attr theme.border_width 6
hc attr theme.floating.border_width 0
hc attr theme.floating.outer_width 0
hc attr theme.floating.outer_color '#55AA88'
hc attr theme.active.inner_color '#77AACC'
hc attr theme.active.outer_color '#77AACC'
hc attr theme.background_color '#55AA88'

hc set auto_detect_monitors 1
hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 1
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 1

# rules
hc unrule -F
hc rule focus=on # normally focus new clients
hc rule class='Chromium' tag=2
hc rule class='code-oss' index=0
hc rule class='Gnome-terminal' index=1
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc set tree_style '╾│ ├└╼─┐'
hc unlock

tint2 &
/usr/lib/xfce4/notifyd/xfce4-notifyd &
fcitx5 &
volumeicon &
flameshot &
picom -b
feh --bg-scale -z -r Pictures/Wallpapers

